version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - "./server/.env"
    environment:
      - NODE_ENV=production